### ISSUE TITLE
Error: invalid Module.php file omeka-s

### ISSUE THREAD

**Issue by AngeloVenera** [Daniel-KM/Omeka-S-module-Ebook#1]
Hi at all,

during the module's installation, omeka-s does this messages:

Error: invalid Module.php file

I have omeka-s ver. 1.3.0, in the directory modules the name of directory is "Omeka-S-module-Ebook", the problem is the name of directory? Or Other?

Thank you Angelo

**Comment by Daniel-KM** [comment]
You should rename the module "Ebook" (this is the namespace of the file Module.php). 
https://github.com/Daniel-KM/Omeka-S-module-Ebook#installation

**Comment by Daniel-KM** [comment]
And try to use the release from here, the master doesn't contain the dependencies (https://github.com/Daniel-KM/Omeka-S-module-Ebook/releases).
