### ISSUE TITLE
Missing parameter "site-slug"

### ISSUE THREAD

**Issue by moodyblue** [Daniel-KM/Omeka-S-module-Ebook#2]
If I try to generate an Ebook for a certain item and:
1) There is no site, and
2) The item includes media

I get the following error:

> Zend\Router\Exception\InvalidArgumentException
> Missing parameter "site-slug"

**Comment by Daniel-KM** [comment]
Yes, indeed. If there is no site, the ebook can not be built, because the links inside it for the items are related to the default site. So I can display a better message, but It's not possible to create an ebook in that case (or perhaps to remove all links to true site).

**Comment by Daniel-KM** [comment]
Thanks, I find the issue. 
This is fixed in last version (3.0.5 for Omeka 1.4, 3.0.6 for Omeka 2).
