### ISSUE TITLE
Ebook call to undifined method

### ISSUE THREAD

**Issue by jomagogo** [Daniel-KM/Omeka-S-module-Ebook#3]
We just installed Ebook module on omeka-s 1.3.0 . Each time we try to create an ebook we get the following error:

Omeka S encountered an error
Error
Call to undefined method Ebook\Form\EbookForm::urlHelper()

Details:

Error: Call to undefined method Ebook\Form\EbookForm::urlHelper() in /var/www/omeka/modules/Ebook/src/Form/EbookForm.php:20
Stack trace:
#0 /var/www/omeka/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerV3Polyfill.php(235): Ebook\Form\EbookForm->init()
#1 /var/www/omeka/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(779): Zend\Form\FormElementManager\FormElementManagerV3Polyfill->callElementInit(Object(Zend\ServiceManager\ServiceManager), Object(Ebook\Form\EbookForm))
#2 /var/www/omeka/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('Ebook\\Form\\Eboo...')
#3 /var/www/omeka/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(141): Zend\ServiceManager\ServiceManager->get('Ebook\\Form\\Eboo...')
#4 /var/www/omeka/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerTrait.php(50): Zend\ServiceManager\AbstractPluginManager->get('Ebook\\Form\\Eboo...', NULL, true)
#5 /var/www/omeka/application/src/Mvc/Controller/Plugin/GetForm.php(33): Zend\Form\FormElementManager\FormElementManagerV3Polyfill->get('Ebook\\Form\\Eboo...', NULL)
#6 [internal function]: Omeka\Mvc\Controller\Plugin\GetForm->__invoke('Ebook\\Form\\Eboo...')
#7 /var/www/omeka/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(276): call_user_func_array(Object(Omeka\Mvc\Controller\Plugin\GetForm), Array)
#8 /var/www/omeka/modules/Ebook/src/Controller/Admin/EbookController.php(190): Zend\Mvc\Controller\AbstractController->__call('getForm', Array)
#9 /var/www/omeka/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Ebook\Controller\Admin\EbookController->createAction()
#10 /var/www/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /var/www/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /var/www/omeka/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 /var/www/omeka/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#14 /var/www/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /var/www/omeka/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /var/www/omeka/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#17 /var/www/omeka/index.php(21): Zend\Mvc\Application->run()
#18 {main}

**Comment by Daniel-KM** [comment]
Hi,
Thanks for your report. It's fixed in version alpha 2 : https://github.com/Daniel-KM/Omeka-S-module-Ebook/releases.
