### ISSUE TITLE
Error before creating an ebook from "Items"

### ISSUE THREAD

**Issue by jomagogo** [Daniel-KM/Omeka-S-module-Ebook#4]
I have found a little bug with Ebook module (version 3.0.1-alpha.2) for Omeka S (version 1.3.0).

When you go to "Items" > (optionally you make an Advanced search) > you select "Create ebook with all" from the dropdown list > and finally you press the "Go" button ...

The message error "You must select at least one resource to create an ebook." is displayed and you aren't addressed to the "Create an eBook" page.

I guess this error would be easy to fix. It seems like no items are selected when you want to select all of them.

However, if you select "Create ebook with selected" at the dropdown list, you can get the ebook (with the maximum of 25 elements that are contained in a single page of items selectable).

**Comment by Daniel-KM** [comment]
It is fixed, i thought that https://github.com/omeka/omeka-s/pull/1260 was integrated.
